classOrder = []
apiCategories = []

# Example VitePress config in TOML format
# [vitepress]
# description = "description"

# NavBar
# [[vitepress.nav]]
# text = "Home"
# link = "/"    # relative paths

# [[vitepress.nav]]
# text = "Docs"

# [[vitepress.nav.items]]
# text = "Nested value"
# link = "/"

# Sidebar
# [[vitepress.sidebar.api]] # global sidebars are NOT supported
# text = "API"
#[[vitepress.sidebar.api.items]]
# text = "API Example"
# link = "/api/apiExample"

# Social Links
# [[vitepress.socialLinks]]
# icon = "github"
# link: "https://github.com/VirtualButFake/moonwave-converter"

# Footer
# [vitepress.footer]
# message = "Made with ❤️ by VirtualButFake"
# copyright = "Copyright (c) 2023"
